### ISSUE TITLE
pywin32 installation fails on macOS

### ISSUE THREAD

**Issue by ozio** [NirDiamant/RAG-Harry-Potter#12]
When attempting to install the project dependencies on macOS, the installation of pywin32 fails with the following error:

```
ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306
```

It appears that pywin32 is a Windows-specific package. Could you please confirm whether this package is indeed only available for Windows? If so, what is the recommended approach for handling this dependency on non-Windows platforms (e.g., macOS or Linux)?

**Comment by nadavox** [comment]
Is someone look into it ?

**Comment by dm1tryG** [comment]
Same issue on my mac

**Comment by yigit353** [comment]
You can relax the version restriction in `requirements.txt` and create a PR @ozio

**Comment by nadavox** [comment]
@yigit353 but from what I checked the pywin32 is only for windows. So how relax the version will help ?

**Comment by NirDiamant** [comment]
I merged @nadavox latest PR. Can we close this issue?

**Comment by ozio** [comment]
Ah nice, thanks @nadavox!
