### ISSUE TITLE
Different methods to obtain Pydantic Objects from LLM

### ISSUE THREAD

**Issue by nprime496** [NirDiamant/RAG-Harry-Potter#20]
Hi, first of all, thank you for your amazing repo.

I've a question regarding the notebook at  https://github.com/NirDiamant/Controllable-RAG-Agent/blob/main/sophisticated_rag_agent_harry_potter.ipynb

I noticed that there's two schemes to obtain python classes from LLMs.

1. using Json Parser

```py
act_possible_results_parser = JsonOutputParser(pydantic_object=ActPossibleResults)
```

2. Using native llm abilities

```py
task_handler_llm.with_structured_output(TaskHandlerOutput)
```

Could you please explain why you used multiple methods in the same notebook when it seems that one method might have been sufficient? And if possible, can you provide more insights into the advantages/disavantages of each method?

**Comment by NirDiamant** [comment]
Sure. 
I prefer using the second option but it works only for LLMs trained on function calling (e.g. GPT series).
I integrated the use of other LLMs that weren't trained on that, so I had to use another way of parsing the models' outputs
