### ISSUE TITLE
Can't run code without pdf example

### ISSUE THREAD

**Issue by lironsoffer** [NirDiamant/RAG-Harry-Potter#7]
`FileNotFoundError: [Errno 2] No such file or directory: 'Harry_Potter_Book_1_The_Sorcerers_Stone.pdf'
`

Would be beneficial to add the file or an example file

**Comment by NirDiamant** [comment]
As for copyrights, I won't be able to upload the book PDF. The Harry Potter book is only used as a case study to demonstrate the controllable RAG agent on a complicated plot and to illustrate the process. While some data preprocessing functions are tailored to this specific PDF, the main concept can be applied to any complex RAG use case that requires such a reasoning process.
